### PR TITLE
update schizo/flux component

### PR DESCRIPTION
**Pull request by garlick**
Drop slurm specific usage modes from schizo/flux component.

### CODE REVIEW

**Comment by garlick** [comment]
@rhc54: this seems to work.   Hopefully I didn't miss anything important?

I have two unexplained observations I want to track down before we call this good.

One is there are always failing `PMI_KVS_Get()` calls on  `2-4294967294-key0`, where the leading `2-` is the jobid. I happened to have our PMI code generating an error log message whenever an unknown key is fetched, which I will suppress since that isn't really an error on the flux side, but I want to be sure the fact that it is missing doesn't indicate some problem with the OpenMPI integration.

Two is a hang observed when I run an openmpi program of size one more than the size of the flux instance.  This doesn't occur when I run a simple PMI program that does size puts, a barrier, then size gets.  This is almost certainly a Flux problem but I'd like to run it down to be sure.

**Comment by garlick** [comment]
> One is there are always failing PMI_KVS_Get() calls on `2-4294967294-key0`

I put up a PMI trace of a size=2 ompi hello world run on flux-framework/flux-core#924.  I observe each rank requesting this key six times in a row.  Any thoughts on what's happening here @rhc54?

**Comment by rhc54** [comment]
In the base functions for the pmix framework, we provide some compaction routines that the different components can use to reduce the number of keys they push into PMI. Cray, for example, has a rather severe constraint on the overall number of keys a job can create. So those routines allow you to aggregate "put" data to save keys, and then separates it all back out when the data is returned.

However, you don't appear to be calling those routines, so I have no idea where that key name is coming from...unless I am just missing some place where you call one of the "pmix_base_..." functions? We wouldn't do that for you, so perhaps this is leftover cruft from the slurm component when we copied it.

**Comment by garlick** [comment]
I'm not sure what I'm looking for but there are a lot of calls to `opal_pmix_base_*()` in here.  Are `opal_pmix_base_store_encoded()`, `opal_pmix_base_partial_commit_packed()`, or `opal_pmix_base_commit_packed()` concerning at all?  I'll have a closer look when I get into work, just I'd ask about those first.

https://github.com/garlick/ompi/blob/a8299717db5a6887a16808649b355029b49d80e7/opal/mca/pmix/flux/pmix_flux.c

**Comment by garlick** [comment]
I have to head out to an appointment, but since the failing get seems to be for a packed key that contains the wildcard rank, could the problem be that `flux_init()` is failing to cache data under some expected key name, and so when it's accessed and is not found, it triggers the PMI get?

We seem to be storing some info with e.g. `opal_pmix_base_store(&wildcard_rank, &kv)` in `flux_init()`.

I don't see an easy way to avoid the "packed" keys since that appears to be the only way to encode/decode opal_value_t values as strings that PMI will ingest.

**Comment by rhc54** [comment]
Yeah, those would be a concern for flux. I'm assuming you haven't created the same problem Cray did by restricting the number of keys in the system? If so, then I'd suggest you just remove all those calls to the base functions and add your own encode/decode to stringify values. You can copy the low-level encode/decode stuff from the base if you like - just bypass the routines that aggregate keys.

**Comment by garlick** [comment]
I think I see what's going on.  Certain `pmix.*` keys are added to the base cache by `flux_init()`.  These keys are fetched back out again later through the cache but if any of the expected keys are not in the cache, it triggers a `PMI_KVS_Get()` for the packed key name.  Not all the expected keys are added by our component.  There are six missing ones corresponding to the six gets noted above:

```
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.lrank
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.nrank
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.max.size
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.job.size
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.appnum
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.local.size
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.num.nodes
0: PMI_KVS_Get ("lwj.0.0.9.pmi", "9-4294967294-key0") rc=4 invalid key argument
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.tmpdir
0: PMI_KVS_Get ("lwj.0.0.9.pmi", "9-4294967294-key0") rc=4 invalid key argument
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.nsdir
0: PMI_KVS_Get ("lwj.0.0.9.pmi", "9-4294967294-key0") rc=4 invalid key argument
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.pdir
0: PMI_KVS_Get ("lwj.0.0.9.pmi", "9-4294967294-key0") rc=4 invalid key argument
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.tdir.rmclean
0: PMI_KVS_Get ("lwj.0.0.9.pmi", "9-4294967294-key0") rc=4 invalid key argument
[jimbo:13684] [[0,9],0] pmix:flux called get for key pmix.ltopo
0: PMI_KVS_Get ("lwj.0.0.9.pmi", "9-4294967294-key0") rc=4 invalid key argument
```
If I get rid of the packed key stuff, I guess that won't fix this since those keys will still not be in the cache.

Although non-fatal, the failing `PMI_KVS_Get()` calls will add startup latency so we should deal with it some way.  Seems like the right solution is to hardwire the `pmix.` prefix so those keys never trigger a `PMI_KVS_Get()` .  Is that safe to do?  I could also try to populate the six missing keys, but that may break as this schema evolves...  Thoughts?

**Comment by garlick** [comment]
Or maybe we could special case the wildcard rank since I think that's only used via the cache?

**Comment by rhc54** [comment]
Hmmm...let me ponder this for a little. I recognize those keys - they are things we pass in for various controls, but most RMs wouldn't do so. I need to look at how we handle the "missing" case to see the best path forward.

**Comment by garlick** [comment]
I went ahead with special casing the wildcard rank, but can back it out if that's not the way to go.

It seems to work, and the extra PMI_KVS_Get() calls are gone.

**Comment by rhc54** [comment]
Yeah, I've been poking at it a bit too, and I think that's just fine. Thanks!

**Comment by garlick** [comment]
Great!  I'll move on the the shared memory hangs.  Let me know if anything I've posted so far needs changing.

**Comment by garlick** [comment]
OK, I think I ran down the shared memory hangs.  It's our fault - in testing we often run a large flux session on one node and use it to launch MPI programs.  Each "node" (as communicated to MPI via PMI clique ranks/PMI_process_mapping) doesn't necessarily have a private /tmp in that case.  I think that is causing shared memory segment names to collide.

I was able to work around it by setting TMPDIR to a different directory on each "Node" (Flux rank).  @rhc54, by chance is there another environment variable that specifically affects vader/shm shared memory segment path generation?  TMPDIR is kind of a big hammer for this.

@trws if you're ready for a test, ralph's branch + this PR should work with flux-core master + flux-framework/flux-core#926.  My testing has been only on one node as described above.

**Comment by garlick** [comment]
Answered our own question -`OMPI_MCA_orte_tmpdir_base` seems to work here.

**Comment by rhc54** [comment]
My apologies for the delay - was in an all-day meeting yesterday and drove home over the mountains today. Yes, that MCA param is the best solution.

**Comment by garlick** [comment]
No worries!  I just did some testing on a PSM2 cluster with 32 nodes, launching MPI up to 1024 ranks and it seems like we're in a good spot with this.  I'd be fine if you want to squash this down and submit upstream for us, or if there's some process you'd like us to follow we can do that.  I'm headed out of town for a week but I'll be checking in.

I don't think this minor work (mostly others code anyway) rises to the level of needing to go through any process or receive a copyright notice from LLNL.

**Comment by rhc54** [comment]
kewl - will bring it across and slate it for OMPI v2.1 release

**Comment by rhc54** [comment]
BTW: LLNL is an official OMPI member (Adam did the paperwork), so if you ever want to add an LLNL copyright, you are welcome to do so.

**Pull request merged**
